/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.hms.explorehms.baseapp.model;

import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;

/**
 * Definition of ObjectType UserInfo.
 *
 * @since 2023-12-06
 */
@PrimaryKeys({"userUid"})
public final class UserInfo extends CloudDBZoneObject {
    private String userUid;

    private String kitName;

    private Integer remainingRequestLimit;

    public UserInfo(String userUid, String kitName, Integer remainingRequestLimit){
        super(UserInfo.class);
        this.userUid = userUid;
        this.kitName = kitName;
        this.remainingRequestLimit = remainingRequestLimit;
    }

    public void setUserUid(String userUid) {
        this.userUid = userUid;
    }

    public String getUserUid() {
        return userUid;
    }

    public void setKitName(String kitName) {
        this.kitName = kitName;
    }

    public String getKitName() {
        return kitName;
    }

    public void setRemainingRequestLimit(Integer remainingRequestLimit) {
        this.remainingRequestLimit = remainingRequestLimit;
    }

    public Integer getRemainingRequestLimit() {
        return remainingRequestLimit;
    }

}
